# RECUERDEN NO IGNORAR ESTE ARCHIVO, O NO LES PODREMOS CORREGIR.
DIAS_COMPETENCIA = 6
# PROBABILIDAD_ACCIDENTARSE_GIMNASIA = 0.3
# COMPLETAR...

# PARÁMETROS DE LA COMPETENCIA
BONUS_MEDALLA = 0.1
MIN_MORAL = 0
MAX_MORAL = 100
MIN_VELOCIDAD = 0
MAX_VELOCIDAD = 100
MIN_RESISTENCIA = 0
MAX_RESISTENCIA = 100
MIN_FLEXIBILIDAD = 0
MAX_FLEXIBILIDAD = 100

UMBRAL_MORAL_FICHAR = 20  # es 20 por enunciado
COSTO_ENTRENAMIENTO = 30
BONUS_MORAL_ENTRENAMIENTO = 1
PUNTOS_ENTRENAMIENTO = 3  # fijado por mi.
# si es n, es raiz a la n la funcion que aumenta el atributo
COSTO_SANAR = 30
COSTO_TECNOLOGIA = 20
BONUS_TECNOLOGIA = 0.1
MAX_HABILIDAD_ESPECIAL = 1
COSTO_HABILIDAD_ESPECIAL = 20

# PARÁMETROS DELEGACIONES

BONUS_IEEE_ENTRENAR = 1.7
MIN_IEEE_EXCE_RESPETO = 0.4
MAX_IEEE_EXCE_RESPETO = 0.8
MIN_IEEE_IMP_DEPORTIVOS = 0.3
MAX_IEEE_IMP_DEPORTIVOS = 0.7
MIN_IEEE_IMP_MEDICOS = 0.2
MAX_IEEE_IMP_MEDICOS = 0.6

MULT_COSTO_DCC_SANAR = 2
MIN_DCC_EXCE_RESPETO = 0.3
MAX_DCC_EXCE_RESPETO = 0.7
MIN_DCC_IMP_DEPORTIVOS = 0.2
MAX_DCC_IMP_DEPORTIVOS = 0.6
MIN_DCC_IMP_MEDICOS = 0.4
MAX_DCC_IMP_MEDICOS = 0.8

# PARÁMETROS DE LOS DEPORTES

IMP_ATLETISMO = False
RIESGO_ATLETISMO = 0.2
IMP_CICLISMO = True
RIESGO_CICLISMO = 0.35
IMP_GIMNASIA = True
RIESGO_GIMNASIA = 0.3
IMP_NATACION = False
RIESGO_NATACION = 0.25

PUNTAJE_MINIMO_DEPORTE = 0
NIVEL_IMPLEMENTOS_COMPETIR = 0.4  # yo fijé este parámetro

ATLETISMO_POND_VEL = 0.55
ATLETISMO_POND_RES = 0.2
ATLETISMO_POND_MOR = 0.25

CICLISMO_POND_VEL = 0.47
CICLISMO_POND_RES = 0.36
CICLISMO_POND_FLE = 0.17

GIMNASIA_POND_FLE = 0.5
GIMNASIA_POND_RES = 0.3
GIMNASIA_POND_MOR = 0.2

NATACION_POND_VEL = 0.45
NATACION_POND_RES = 0.3
NATACION_POND_FLE = 0.25
